apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace

---

apiVersion: v1
kind: Service
metadata:
  namespace: test-namespace
  name: webapp
spec:
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-namespace
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 'acrmcataniatestwesteu.azurecr.io/catania:40263'
        ports:
        - containerPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test-namespace
  name: azure-agw-ingress
spec:
  ingressClassName: azure/application-gateway
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: webapp
            port: 
              number: 80

